version: '2'
services:
  gui:
    image: openvpn-web-gui:latest
    container_name: openvpn-web-gui
    environment:
      - OPENVPN_ADMIN_USERNAME=admin
      - OPENVPN_ADMIN_PASSWORD=b3secure
      - PIVPN_SERVER=${PIVPN_SERVER}
      - PIVPN_CONF=${PIVPN_CONF}
      - TZ=${TZ}
      - ENABLEHTTPS=${ENABLEHTTPS}
      - HTTPSPORT=${HTTPSPORT}
      - HTTPSCERT=${HTTPSCERT}
      - HTTPSKEY=${HTTPSKEY}
    ports:
       - "8080:8080/tcp"
       - "8443:8443/tcp"
    restart: always
    volumes:
       - /etc/openvpn:/etc/openvpn
       - ./openvpn-data/db:/opt/openvpn-gui-tap/db
       
